# Setup
title:               Dudley Dev Diaries
tagline:             'Musings of a mobile dev'
description:         'A blog for iOS development and other fun tech'
url:                 https://nathandud.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nathan Dudley
  url:               https://twitter.com/nathandud
  email:             nathan@dudleydev.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
